### ISSUE TITLE
The system cannot find the path specified:

### ISSUE THREAD

**Issue by sparkmobi** [IShallRiseAgain/AIStoryGen#1]
i am getting this error after running GenerateVideoFromGPT.py

> File "G:\AIStoryGen\GenerateVideoFromGPT.py", line 33, in <module>
    GenerateVideo.Generate(text,config)
  File "G:\AIStoryGen\GenerateVideo.py", line 47, in Generate
    path=BackupText(text, config)
  File "G:\AIStoryGen\GenerateVideo.py", line 34, in BackupText
    os.mkdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'output\\__Once_upo_03_07_2023_03_34_21'

**Comment by IShallRiseAgain** [comment]
fixed it so the output folder will be created if it doesn't exist.
